### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Drish83** [Arhosseini77/Brand_Attention#16]
I am trying to run the inference section in colab notebook, but when I try to test other images it gives this error . 
![Screenshot 2024-06-03 125501](https://github.com/Arhosseini77/Brand_Attention/assets/113623235/9e8d617f-6573-482f-9d44-74b4553f2d62)

even though the file is present.

**Comment by K-Hooshanfar** [comment]
Hi, make sure you specify the paths correctly.

**Comment by K-Hooshanfar** [comment]
Hi, make sure you specify the paths correctly.
